remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-remote-theme

title: Rainy Chen
description: >
  Hi, I'm majoring in statistics with a double minor in computer science and mathematics at the University of Toronto.  
  I'm currently the finance and internal operations director of UTMIST. I'm interested in analyzing financial data and researching about optimizing the accuracy of LLMs.

nav:
  - title: "About"
    url: /about/
  - title: "Education"
    url: /education/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/

sass:
  sass_dir: assets/css

...
url: "https://rainycore.github.io"
github: [metadata]

